name: Build Example PDF files

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Tectonic Cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/Tectonic
        key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
        restore-keys: |
          ${{ runner.os }}-tectonic-
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
    - name: Setup Pandoc
      env: 
        PDC_VER: '2.16.1'
      run: |
        wget -qO- https://github.com/jgm/pandoc/releases/download/${PDC_VER}/pandoc-${PDC_VER}-linux-amd64.tar.gz | sudo tar xzf - --strip-components 1 -C /usr/local/
    - name: Setup tectonic LaTeX engine
      uses: wtfjoke/setup-tectonic@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
    - name: Setup Python dependencies
      run: python -m pip install pandoc-latex-environment
    - name: Setup fonts and image convertion tool
      run: sudo apt-get update -qq && sudo apt-get install fonts-noto-cjk poppler-utils -y
    - name: Build pdf files
      run: cd examples && bash build-examples.sh && cd ..
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-files
        path: |
          examples/*/document.pdf
          examples/*/preview.png
    - name: Build index page
      run: |
        pandoc --standalone ./examples/index.md -o ./examples/index.html
    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v3.8.0
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force_orphan: false
        publish_dir: ./examples
